// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String rAW;
String ubloxAlt;
String ubloxLat;
String ubloxLong;
String ubloxTime;
int timeUTC;
CloudLocation coordMAP;

void initProperties(){

  ArduinoCloud.addProperty(rAW, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(ubloxAlt, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(ubloxLat, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(ubloxLong, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(ubloxTime, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(timeUTC, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(coordMAP, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
